Add skos definitions
buda-base/owl-schema pull request #187
Opened 2021-06-20 19:32 UTC by rjyounes

Added two additional skos definitions, for bdo:Gender and bdo:personGender.

2021-08-04 13:47 UTC, rjyounes commented
@eroux Just a nudge on this one.

2021-08-04 13:48 UTC, eroux requested changes

2021-08-04 13:48 UTC, eroux commented
oops, I commented a while ago but it seems I haven't clicked on the right button sorry!

2021-08-04 14:20 UTC, rjyounes commented on core/bdo.ttl
> +	skos:definition "A category into which humans are divided on the basis of their reproductive functions."@en ;
Is the difference between biological sex and gender identity ever relevant in this knowledge domain?

2021-08-04 14:37 UTC, eroux commented on core/bdo.ttl
> +	skos:definition "A category into which humans are divided on the basis of their reproductive functions."@en ;
I can't think of any case where we would want to assert something terribly specific here... I think we would be safe with an inclusive definition

2021-12-30 21:43 UTC, eroux requested changes
Thanks! The skos definitions are good, can you put the changes to the scripts in a separate PR? (Also they look a bit off)

2022-04-05 15:40 UTC, closed without merging